### ISSUE TITLE
Basic installation

### ISSUE THREAD

**Issue by bartolije** [simplethings/EntityAuditBundle#263]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no

During installation, the line in the config.yml make the bundle bugged.
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized option "entity_manager" under "simple_things_entity_audit"
```

I finally removed the line, and it worked. Or at least, no more error.
Just after, I run into an issue with the annotation in my entity.

```
use Doctrine\ORM\Mapping as ORM;
use SimpleThings\EntityAudit\Mapping\Annotation as Audit;

/**
 * @ORM\Entity()
 * @Audit\Auditable()
 */
class Page {
 //...
}
```
Even with some research, I didn't found any `\Mapping\Annotation` folder. I guess an update updated it, so is there a way to know how to deal with, or how to work with that?

**Comment by smoench** [comment]
@bartolije Which version have you installed?

**Comment by DavidBadura** [comment]
Please use the version 1.x. You can find the documentation here: https://github.com/simplethings/EntityAuditBundle/blob/1.0/README.md

**Comment by bartolije** [comment]
Installed the master version.
Kinda better with 1.0 version, but will need more research about some functionnalities not working as expected. (but probably come from a wrong implementation)(see entity diff, etc).
Thank you for replies..
