### ISSUE TITLE
`use SimpleThings\EntityAudit\Mapping\Annotation as Audit` does not work.

### ISSUE THREAD

**Issue by gustawdaniel** [simplethings/EntityAuditBundle#271]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

I catalog structure of bundle downloaded by `composer` there is no `Mapping` catalog

![](http://i.imgur.com/a81W7Ko.png) 

When on github and in documentation there is this catalog and file `Auditable.php`

![](http://i.imgur.com/G2OKoRo.png)

Proposed solution:

Update package in composer.

**Comment by tolry** [comment]
@gustawdaniel are you using a stable release with composer? Annotation support is not yet in a stable release, will be included in version 2.0 /cc @DavidBadura

**Comment by gustawdaniel** [comment]
In my composer there is:

    "simplethings/entity-audit-bundle": "^1.0"

I was installing it by command from `master`.

    composer require simplethings/entity-audit-bundle

If I understand you correctly. Should I use documentation form `1.0`? Not master?

**Comment by tolry** [comment]
> composer require simplethings/entity-audit-bundle
does install - depending on your composer version - a stable version, so e.g. `^1.0`

The annotation feature is **not** yet released as a stable feature. You might try it (and lots of other changes) by using the master branch by using the following composer command

> composer require simplethings/entity-audit-bundle dev-master

But this is not encouraged, as master might be in a broken state at any time and happens at your own risk. If you would like to use annotations in a stable release, you will have to wait a little bit longer (I think, @DavidBadura has not yet decided on a release date).

**Comment by DavidBadura** [comment]
@gustawdaniel yes, please use version `^1.0` and this documentation: https://github.com/simplethings/EntityAuditBundle/blob/1.0/README.md

As @tolry said, master (2.0) isn't ready yet. This month, I don't have time to work on it, sorry. But I will try to release 2.0 around Easter.

**Comment by DavidBadura** [comment]
I have tried to clarify the status of master in the readme: https://github.com/simplethings/EntityAuditBundle/commit/71691cef9ab82aff326ba2689784b88ccc0a2ef7

I will close this issue because it isn't a bug.
