### ISSUE TITLE
AuditManager is not instantiated automatically (v. 2.0)

### ISSUE THREAD

**Issue by AlexeyKosov** [simplethings/EntityAuditBundle#278]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

When using it as a Symfony Bundle, AuditManager has to be created manually or injected into some used service, otherwise it's not constructed and therefore no event listeners are registered.

**Comment by DavidBadura** [comment]
version 2.0 ist in development. please use 1.x.
