### ISSUE TITLE
Packagist version

### ISSUE THREAD

**Issue by AlexeyKosov** [simplethings/EntityAuditBundle#279]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

Looks like v.1.0.3 in packagist contains the dev-master (v.2) branch and therefore doesn't work.
https://packagist.org/packages/simplethings/entity-audit-bundle#v1.0.3

**Comment by DavidBadura** [comment]
oh man :-( thank you very much! should be fixed with version 1.0.4
