### ISSUE TITLE
The rev column is hard coded in queries

### ISSUE THREAD

**Issue by c0ntax** [simplethings/EntityAuditBundle#280]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

The configuration of this bundle allows you to change the column name used for 'rev' but it's hard coded in places so if you do change your configuration, it breaks your ability to see revisions (in Sonata)

**Comment by c0ntax** [comment]
Added a pull request for this fix: https://github.com/simplethings/EntityAuditBundle/pull/281

**Comment by DavidBadura** [comment]
v1.0.5 released!
