### ISSUE TITLE
Support for Symfony 3?

### ISSUE THREAD

**Issue by lutrasdebtra** [simplethings/EntityAuditBundle#282]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Question? | yes

Haven't been able to find any information on whether this bundle currently supports Symfony version 3.\*.\*, or if it is planned for the future.

**Comment by DavidBadura** [comment]
Hello @lutrasdebtra , it should support ^2.8 and ^3.0. 

See https://travis-ci.org/simplethings/EntityAuditBundle/builds/236346805

**Comment by braianj** [comment]
it´s support 3.3?

**Comment by tolry** [comment]
@braianj as you can see from the travis runs, only 3.2 was tested so far, but since their "should" be no BC breaks in minor versions of symfony, 3.3 shoudl work out of the box.

If you experience any problems, please take the time to write a separate issue - thx 👍
