### ISSUE TITLE
Default Username null not allowed if token username not set in 1.0.5

### ISSUE THREAD

**Issue by aggayush** [simplethings/EntityAuditBundle#286]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes

- If username is not set in token storage, like in a command. Previous versions were having default username as blank string which was getting saved. Now, it throws NULL error.
- Back compatibility is breaking.

**Comment by DavidBadura** [comment]
Thanks for reporting. Which version did you have before?

**Comment by aggayush** [comment]
We were using 0.7 before. Now switched to 1.0.5

**Comment by tolry** [comment]
Havin the same problem here, when upgrading from `^0.9` to `1.0.5` - investigating

**Comment by tolry** [comment]
Hmm, this looks correct https://github.com/simplethings/EntityAuditBundle/blob/v1.0.5/src/SimpleThings/EntityAudit/EventListener/CreateSchemaListener.php#L112

But doesn't seem to work or the code is not even executed?

**Comment by tolry** [comment]
Ok, the `setNotnull()` works, but this is a new(ish) thing. So previously the username would always be a string. If the username was unknown, it would be an empty string, but never null.

So one way to fix this would be to run a migration and get an `ALTER TABLE` for the username column allowing NULL. But I would still consider this a BC break.

The responsible commit is the following

https://github.com/simplethings/EntityAuditBundle/commit/4640b8ed8fcab3e40d30b6f45253285d5faeb421

In this commit, we made the way configurable, how the username is obtained (#187) and if no callable was set (or the old setUsername() was not called) it would return null

``` php
return $callable ? $callable() : null;
````

I personally do not see any merit in `null` over an empty string for a string column (so, no real FK anyway) and would like to return to the old behaviour. Any comments/objections @bendavies (committer) or @ocramius (issue creator)?

**Comment by tolry** [comment]
I will prepare a PR shortly

**Comment by Ocramius** [comment]
@tolry in SQL, null is a very precise concept ("absence" of a value)

**Comment by tolry** [comment]
@ocramius, yes and for 2.x I might agree that this is more precise than an empty string. But forcing users to run a migration for patch level upgrades I would really like to prevent.

**Comment by Ocramius** [comment]
@tolry no, indeed, for a patch version there should be no user interaction needed to upgrade.

**Comment by bendavies** [comment]
(Y)

**Comment by DavidBadura** [comment]
fixed in [v1.0.6](https://github.com/simplethings/EntityAuditBundle/releases/tag/v1.0.6)
