### ISSUE TITLE
Problem with Detail Action

### ISSUE THREAD

**Issue by sw4n** [simplethings/EntityAuditBundle#288]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?

When trying to get audited entity details for this example route:
`/audit/viewent/AuditedEntityExample/15/29032`
I'm getting doctrine exception:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.0' in 'where clause'

I've found this route while debugging:
https://github.com/simplethings/EntityAuditBundle/blob/master/src/SimpleThings/EntityAudit/Resources/config/routing.yml#L17

Which relates to this action:
https://github.com/simplethings/EntityAuditBundle/blob/master/src/SimpleThings/EntityAudit/Controller/AuditController.php#L120

On this line explode function will return bool or array, which eventually passing to this:
https://github.com/simplethings/EntityAuditBundle/blob/master/src/SimpleThings/EntityAudit/AuditReader.php#L175

And gives "0" as select field. Can you fix this?

**Comment by tolry** [comment]
@sw4n a few questions

* which version are you using: caution, master is currently **not** stable/usable
* which Symfony version are you using?

**Comment by sw4n** [comment]
@tolry I'm using v1.0.5 and Symfony v2.8.17

**Comment by sw4n** [comment]
@tolry can you give any feedback about this?

**Comment by mhnrm** [comment]
Same issue here, is there any progress in this?

I'm currently using version 1.0.6 of the AuditBundle and Symfony 2.8.25.

**Comment by cirovargas** [comment]
Same here Bundle version 1.0.6, symfony 3.3.9

**Comment by Ballihaut** [comment]
Hi,
we are facing to the same  
I see this issue is open since for a wild. 
Did this issue have a definive fix, we don't have identify ?

**Comment by helmuthva** [comment]
same here.

**Comment by helmuthva** [comment]
Same here:

2018-05-06 10:56:56] app.DEBUG: hosts from env {"hosts":"localhost:9200"} []
 --------------------- --------------------------------------------------------------------------------------------- 
  Symfony                                                                                                            
 --------------------- --------------------------------------------------------------------------------------------- 
  Version               4.0.9                                                                                        
  End of maintenance    07/2018                                                                                      
  End of life           01/2019                                                                                      
 --------------------- --------------------------------------------------------------------------------------------- 
  Kernel                                                                                                             
 --------------------- --------------------------------------------------------------------------------------------- 
  Type                  App\Kernel                                                                                   
  Name                  src                                                                                          
  Environment           dev                                                                                          
  Debug                 true                                                                                         
  Charset               UTF-8                                                                                        
  Root directory        ./src                                                                                        
  Cache directory       ./var/cache/dev (30.6 MiB)                                                                   
  Log directory         ./var/log (0 B)                                                                              
 --------------------- --------------------------------------------------------------------------------------------- 
  PHP                                                                                                                
 --------------------- --------------------------------------------------------------------------------------------- 
  Version               7.1.16                                                                                       
  Architecture          64 bits                                                                                      
  Intl locale           de_DE                                                                                        
  Timezone              Europe/Berlin (2018-05-06T10:56:56+02:00)                                                    
  OPcache               true                                                                                         
  APCu                  true                                                                                         
  Xdebug                true            

Btw: had to 

			$auditManager = $container->findDefinition('simplethings_entityaudit.reader');
			$auditManager->setPublic(true);

to make it run with Sf4
